@baseUrl = https://longobuccodev.com.br/api/contact-book
@token = {{autenticate.response.body.accessToken}}

###
POST {{baseUrl}}/user
Content-Type: application/json

{
    "name": "Fabrício Longo Bucco Pinheiro",
    "cpf": "12356544324",
    "email": "longobuccoofbc@gmail.com",
    "password": "12345897897",
    "birthday": "1988-11-7"
}

###
# @name autenticate
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "email": "longobuccoofbc@gmail.com",
  "password": "12345897897"
}

###
GET {{baseUrl}}/user/2
Authorization: Bearer {{token}}


###
GET {{baseUrl}}/user
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/contact/user/2
Authorization: Bearer {{token}}


###
POST  {{baseUrl}}/contact/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name":"Fabrici",
    "number":"21969789088"
}

###
PATCH   {{baseUrl}}/contact/1
Authorization: Bearer {{token}}
Content-Type: application/json

{   
    "name":"irmão"
}