@baseUrl = https://longobuccodev.com.br/api/contact-book
@token = {{autenticate.response.body.accessToken}}

###
POST {{baseUrl}}/user
Content-Type: application/json

{
    "name": "Stéfani Longo Bucco Pinheiro",
    "cpf": "43536766543",
    "email": "tetezinha@gmail.com",
    "password": "1234589789",
    "birthday": "1992-5-11"
}

###
# @name autenticate
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "email": "tetezinha@gmail.com",
  "password": "1234589789"
}

###
GET {{baseUrl}}/user/3
Authorization: Bearer {{token}}


###
GET {{baseUrl}}/user
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/contact/user/3
Authorization: Bearer {{token}}


###
POST  {{baseUrl}}/contact/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name":"setio",
    "number":"21989887783"
}

###
PATCH   {{baseUrl}}/contact/3
Authorization: Bearer {{token}}
Content-Type: application/json

{   
    "name":"irmão"
}